### ISSUE TITLE
Misspelled library in the description

### ISSUE THREAD

**Issue by Querijn** [systeme-cardinal/Pyke#1]
Nothing huge, but library is misspelled :)
![image](https://user-images.githubusercontent.com/3397066/42984987-b099b98c-8bef-11e8-8393-2982e6989e19.png)

**Comment by systeme-cardinal** [comment]
Sorry my English is not good but I try, i change description, she is little but explicit

**Comment by Querijn** [comment]
Don't worry! I completely understand, that's why I am here to help :)

I'm suggesting the change from librairie to library

So that would make the current description
`Library NodeJS with RiotAPI and DDragon`.

**Comment by systeme-cardinal** [comment]
Thx Man :)

**Comment by Querijn** [comment]
Whoops! I just realised that in English it's reversed.. I'm stupid. Sorry!

`Riot API and DDragon Library for NodeJS` is probably close to what you're looking for. I'll stop bothering you now..
